CREATE DATABASE AMAZON_DB;
USE AMAZON_DB;
SELECT * FROM Ele_Stores;

--1. Total Sales and Profit per Product:
SELECT ProductName, SUM(Sales) AS TotalSales, SUM(Profit) AS TotalProfit
FROM Ele_Stores
GROUP BY ProductName
ORDER BY TotalSales DESC;

--Calculates total sales and total profit for each product. The result is sorted by total sales in descending order to highlight the top-selling products.

--2. Top 5 Most Profitable Products Globally:
SELECT TOP 5 ProductName, SUM(Profit) AS TotalProfit
FROM Ele_Stores
GROUP BY ProductName
ORDER BY TotalProfit DESC;

--Finds the top 5 products by total profit across all regions.

--3. Sales Distribution by Region:
SELECT Region, SUM(Sales) AS TotalSales, SUM(Profit) AS TotalProfit
FROM Ele_Stores
GROUP BY Region;

--Shows the total sales and profit for each region.

--4.Top 3 Countries with Highest Sales:
SELECT TOP 3 Country, SUM(Sales) AS TotalSales
FROM Ele_Stores
GROUP BY Country
ORDER BY TotalSales DESC;

--Identifies the top 3 countries contributing the most to total sales.

--5. Monthly Sales Trend:
SELECT FORMAT(OrderDate, 'yyyy-MM') AS Month, SUM(Sales) AS MonthlySales
FROM Ele_Stores
GROUP BY FORMAT(OrderDate, 'yyyy-MM')
ORDER BY Month;

-- Displays sales trends on a monthly basis by grouping sales by year and month.

--6. Top Promotion by Profit:
SELECT PromotionName, SUM(Profit) AS TotalProfit
FROM Ele_Stores
GROUP BY PromotionName
ORDER BY TotalProfit DESC;

--Shows which promotion generated the highest profit by summing profits per promotion.

--7. Product Sales Performance in Each Region:
SELECT Region, 
       ProductName, 
       SUM(Sales) AS TotalSales
FROM Ele_Stores
GROUP BY Region, ProductName
ORDER BY Region, TotalSales DESC;

--Analyzes how each product performed in different regions by displaying the total sales per region.

--8. Most Popular Sales Channel:
SELECT Channel, COUNT(OrderID) AS TotalOrders
FROM Ele_Stores
GROUP BY Channel
ORDER BY TotalOrders DESC;

-- Counts the number of orders for each sales channel (Store or Online) to find the most popular channel.

-- 9. Average Profit per Order by Channel:
SELECT Channel, 
       AVG(Profit) AS AvgProfitPerOrder
FROM Ele_Stores
GROUP BY Channel;

-- Calculates the average profit made from orders in each sales channel.

--10. Total Cost of Sales per Product Category:
SELECT ProductCategory, 
       SUM(CostOfSales) AS TotalCostOfSales
FROM Ele_Stores
GROUP BY ProductCategory;

--Shows the total cost of sales for each product category.

--11. Orders Shipped to Moscow:
SELECT * 
FROM Ele_Stores
WHERE City = 'Moscow';

--Retrieves all orders shipped to the city of Moscow.

--12. Top Manufacturer by Sales:
SELECT Manufacturer, 
       SUM(Sales) AS TotalSales
FROM Ele_Stores
GROUP BY Manufacturer
ORDER BY TotalSales DESC;

--13. Profitability of Each Product Category:
SELECT ProductCategory , SUM(Profit) AS TotalProfit
FROM Ele_Stores
GROUP BY ProductCategory
ORDER BY TotalProfit DESC;

--Displays the total profit made from each product category.

--14. Sales in the Last Quarter (September 2017):
SELECT * FROM Ele_Stores
WHERE OrderDate >= '2017-09-01'
      AND
      OrderDate <= '2017-09-30';

--Fetches all sales data from September 2017, representing the last quarter of available data.

--15. Profit to Cost Ratio for Each Product:
SELECT ProductName, 
       SUM(Profit) / SUM(CostOfSales) AS ProfitCostRatio
FROM Ele_Stores
GROUP BY ProductName
ORDER BY ProfitCostRatio DESC;

--Calculates the ratio of profit to cost of sales for each product.

--16. Highest Sales Day:
SELECT TOP 1 OrderDate, 
             SUM(Sales) AS TotalSales
FROM Ele_Stores
GROUP BY OrderDate
ORDER BY TotalSales DESC;

--Identifies the day with the highest total sales.

--17. Total Revenue Generated by Store Channel:
SELECT SUM(Sales) AS StoreSales
FROM Ele_Stores
WHERE Channel = 'Store';

--This query calculates the total sales generated by the Store sales channel by summing the Sales where Channel equals 'Store'.

--18. Product with Highest Unit Cost:
SELECT TOP 1 ProductName, 
             UnitCost
FROM Ele_Stores
ORDER BY UnitCost DESC;

--This query retrieves the product with the highest UnitCost by ordering the UnitCost in descending order and returning the top result.

--19. Region with Lowest Average Profit:
SELECT TOP 1 Region, 
             AVG(Profit) AS AvgProfit
FROM Ele_Stores
GROUP BY Region
ORDER BY AvgProfit ASC;

--This query returns the region with the lowest average profit by averaging the Profit for each Region and ordering the result in ascending order to get the lowest value.

--20. Discounted vs. Non-Discounted Promotions:
SELECT PromotionName, 
       SUM(Sales) AS TotalSales
FROM Ele_Stores
GROUP BY PromotionName
HAVING PromotionName LIKE '%Discount%';

--This query returns the total sales for all promotions that include the word 'Discount' in their PromotionName, comparing discount promotions.

--21. Order Count for Each City:
SELECT City, 
       COUNT(OrderID) AS OrderCount
FROM Ele_Stores
GROUP BY City
ORDER BY OrderCount DESC;

-- This query counts the number of orders for each city by counting the OrderID for each City and ordering by the highest order count.

--22. Cumulative Sales by Product (Running Total):
SELECT ProductName, 
       SUM(SUM(Sales)) OVER (ORDER BY ProductName) AS RunningTotalSales
FROM Ele_Stores
GROUP BY ProductName;

-- This query calculates a running total of sales for each product using the window function OVER, showing cumulative sales as the products are ordered.

--23.Product Sales Performance in Asia Region:
SELECT ProductName, SUM(Sales) AS TotalSales
FROM Ele_Stores
WHERE Region = 'Asia'
GROUP BY ProductName
ORDER BY TotalSales DESC;

--This query returns the sales performance for products sold in the Asia region by filtering for Region = 'Asia' and grouping the data by ProductName.

--24. Average Order Quantity per Product:
SELECT ProductName, 
       AVG(OrderQty) AS AvgOrderQty
FROM Ele_Stores
GROUP BY ProductName;

--This query calculates the average quantity of orders for each product by averaging the OrderQty for each ProductName.

--25. Total Sales and Profit by Promotion:
SELECT PromotionName, 
       SUM(Sales) AS TotalSales, 
       SUM(Profit) AS TotalProfit
FROM Ele_Stores
GROUP BY PromotionName;

--This query sums the total sales and profit for each promotion by grouping by PromotionName and summing both Sales and Profit values for each promotion.

--26. Profit Margin by Region and Product Category:
SELECT Region, 
       ProductCategory, 
       SUM(Profit) AS TotalProfit, 
       SUM(Sales) AS TotalSales,
       (SUM(Profit) / SUM(Sales)) * 100 AS ProfitMarginPercentage
FROM Ele_Stores
GROUP BY Region, ProductCategory
ORDER BY ProfitMarginPercentage DESC;

--This query calculates the profit margin as a percentage for each Region and ProductCategory. It divides total profit by total sales and multiplies it by 100 to get the margin in percentage. It orders the result by profit margin, which allows identification of the most profitable regions and product categories.

--27. Cumulative Sales and Running Total of Profit by Region:
SELECT Region, 
       SUM(Sales) AS TotalSales, 
       SUM(SUM(Profit)) OVER (ORDER BY Region) AS RunningTotalProfit
FROM Ele_Stores
GROUP BY Region
ORDER BY Region;

--This query shows the cumulative (running total) profit for each region. It uses the window function SUM() OVER() to calculate the running total of profit as the query processes each region. This is useful for tracking how the total profit accumulates across different regions.

--28. Top 5 Products by Profit per Order and Their Sales Channel:
SELECT TOP 5 ProductName, 
              Channel, 
              AVG(Profit / OrderQty) AS ProfitPerOrder
FROM Ele_Stores
GROUP BY ProductName, Channel
ORDER BY ProfitPerOrder DESC;

--29. Sales and Profit Breakdown by Region, City, and Channel:
SELECT Region, 
       City, 
       Channel, 
       SUM(Sales) AS TotalSales, 
       SUM(Profit) AS TotalProfit
FROM Ele_Stores
GROUP BY Region, City, Channel
ORDER BY Region, City, TotalSales DESC;

--This query gives a hierarchical breakdown of sales and profit by region, city, and channel. It groups the data first by region, then by city within that region, and finally by sales channel. The results are ordered by region and city with sales in descending order to show the best-performing locations and channels.

--30. Top 3 Most Profitable Manufacturers in Each Region:
WITH ManufacturerProfit AS (
    SELECT Region, 
           Manufacturer, 
           SUM(Profit) AS TotalProfit,
           ROW_NUMBER() OVER (PARTITION BY Region ORDER BY SUM(Profit) DESC) AS ProfitRank
    FROM Ele_Stores
    GROUP BY Region, Manufacturer
)
SELECT Region, Manufacturer, TotalProfit
FROM ManufacturerProfit
WHERE ProfitRank <= 3;

--This query identifies the top 3 most profitable manufacturers in each region. It uses the ROW_NUMBER() window function to rank manufacturers by profit within each region (PARTITION BY Region). The outer query then filters to show only the top 3 manufacturers per region.
